"""Add VideoStatus

Revision ID: 94fa91cd14b0
Revises: 8e2f6774079a
Create Date: 2025-08-03 20:34:13.580686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94fa91cd14b0'
down_revision: Union[str, None] = '8e2f6774079a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_tokens_id', table_name='email_tokens')
    op.drop_index('ix_users_id', table_name='users')
    op.add_column('videos', sa.Column('created_by_id', sa.Integer(), nullable=False))
    op.alter_column('videos', 'title',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('videos', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('videos', 'duration',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'videos', ['s3_key'])
    op.drop_constraint('videos_user_id_fkey', 'videos', type_='foreignkey')
    op.create_foreign_key(None, 'videos', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.drop_column('videos', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'videos', type_='foreignkey')
    op.create_foreign_key('videos_user_id_fkey', 'videos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'videos', type_='unique')
    op.alter_column('videos', 'duration',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('videos', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('videos', 'title',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_column('videos', 'created_by_id')
    op.create_index('ix_users_id', 'users', ['id'], unique=False)
    op.create_index('ix_email_tokens_id', 'email_tokens', ['id'], unique=False)
    # ### end Alembic commands ###
