"""remove created_by_id from videos

Revision ID: f1ed9b1bea93
Revises: 94fa91cd14b0
Create Date: 2025-08-03 20:45:32.565613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1ed9b1bea93'
down_revision: Union[str, None] = '94fa91cd14b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('videos_created_by_id_fkey', 'videos', type_='foreignkey')
    op.drop_column('videos', 'created_by_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('created_by_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('videos_created_by_id_fkey', 'videos', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
